package com.example.cms4j.sample;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

// Run this ddl script to generate table.
// syntax -> db.schema.table_name
// CREATE TABLE public.sample_article
//        (
//        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        title VARCHAR(140) NOT NULL,
//        content VARCHAR(400)
//        );

@Table("sample_article")
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class SampleArticleEntity {

    @Id
    private int id;
    private String title;
    private String content;
}
